site_name: Ivan's Blog
site_url: https://ivanleo.com
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
plugins:
  - social
  - search
  - blog:
      blog_toc: true
      authors_file: "{blog}/.authors.yml"
      post_url_format: "{slug}"
  - rss:
      match_path: docs/blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: G-MM8QMY5JWN
